package com.herokuapp.navio.resource;


/**
 * �?ストに出す英単語と意味(日本語訳)を保持するクラス
 * 単語�?�ターゲ�?�?1900から
 */
public class WordsAndMeanings {
	// 英単�?
	public static String[] words = { "", "improve", "relate", "provide", "consider", "include", "concern", "involve",
			"produce", "allow", "require", "appear", "tend", "agree", "describe", "add", "depend", "encourage", "exist",
			"reduce", "adapt", "compare", "increase", "suggest", "cost", "share", "wonder", "argue", "realize",
			"control", "affect", "find", "notice", "avoid", "force", "offer", "demand", "claim", "deal", "store",
			"complete", "value", "benefit", "opportunity", "quality", "author", "technology", "environment", "view",
			"situation", "effect", "influence", "term", "skill", "theory", "issue", "subject", "article", "statement",
			"experiment", "figure", "evidence", "industry", "economy", "medicine", "matter", "material", "species",
			"practice", "focus", "memory", "right", "accord", "thought", "interest", "account", "cause", "sound",
			"individual", "certain", "possible", "likely", "available", "social", "public", "physical", "scientific",
			"common", "general", "particular", "similar", "various", "native", "patient", "recent", "even", "yet",
			"rather", "instead", "simultaneously", "each", "challenge", "determine", "manage", "maintain", "refer",
			"approach", "advance", "express", "spread", "occur", "observe", "recognize", "suppose", "regard", "treat",
			"search", "prove", "establish", "mention", "represent", "prefer", "apply", "seek", "publish", "perform",
			"gain", "fit", "contain", "supply", "prepare", "bear", "prevent", "object", "decline", "replace", "connect",
			"attend", "survive", "respect", "waste", "advantage", "resource", "medium", "method", "attitude",
			"structure", "function", "feature", "aspect", "content", "detail", "range", "region", "trade", "habit",
			"cell", "fuel", "bill", "charge", "fine", "temperature", "decade", "emotion", "explanation", "solution",
			"degree", "access", "contrast", "status", "surface", "conflict", "audience", "clay", "epoch", "profit",
			"income", "ancestor", "crop", "significant", "necessary", "appropriate", "correct", "worth", "positive",
			"plastic", "political", "official", "private", "ancient", "due", "complex", "mobile", "blank", "male",
			"therefore", "thus", "eventually", "otherwise", "despite", "both", "succeed", "identify", "reflect",
			"assume", "estimate", "define", "indicate", "reveal", "attempt", "respond", "associate", "examine",
			"address", "trust", "doubt", "ignore", "refuse", "complain", "decrease", "vary", "emerge", "match", "stick",
			"hide", "attract", "promote", "satisfy", "earn", "preserve", "enable", "destroy", "tear", "suffer",
			"survey", "divide", "conduct", "graduate", "contribute", "desire", "relax", "target", "aim", "principle",
			"norm", "strategy", "track", "progress", "personality", "characteristic", "manner", "device", "origin",
			"gene", "atmosphere", "trend", "phenomenon", "context", "circumstance", "pain", "struggle", "pollution",
			"threat", "disaster", "consequence", "revolution", "majority", "mass", "stock", "wealth", "literature",
			"authority", "institution", "custom", "sight", "display", "colleague", "resident", "vehicle", "essential",
			"aware", "mental", "academic", "ordinary", "familiar", "novel", "specific", "chemical", "financial",
			"active", "negative", "direct", "obvious", "current", "urban", "furthermore", "likewise", "though",
			"nevertheless", "thereby", "hence", "appreciate", "admit", "predict", "acquire", "adopt", "purchase",
			"afford", "consume", "remove", "suit", "expand", "extend", "explore", "judge", "demonstrate", "insist",
			"appeal", "convince", "settle", "aid", "educate", "engage", "combine", "organize", "operate", "recall",
			"rely", "amaze", "confuse", "blame", "criticize", "behave", "encounter", "select", "flow", "evolve",
			"freeze", "release", "locate", "advertise", "imagination", "perspective", "confidence", "achievement",
			"reward", "corporation", "capital", "client", "crisis", "harm", "victim", "option", "campaign", "court",
			"code", "criminal", "agriculture", "religion", "philosophy", "conference", "document", "statistics",
			"analysis", "hypothesis", "notion", "stereotype", "review", "vocabulary", "organ", "gender", "fossil",
			"glacier", "laboratory", "virus", "occasion", "minister", "presence", "substance", "creative", "potential",
			"independent", "willing", "efficient", "ideal", "genetic", "entire", "relative", "extreme", "vast", "tiny",
			"desert", "rural", "previous", "legal", "nowadays", "seldom", "meanwhile", "latter", "versus", "all",
			"perceive", "expect", "intend", "request", "remind", "inspire", "fascinate", "emphasize", "recommend",
			"propose", "distinguish", "complicate", "transform", "credit", "reserve", "oppose", "deny", "reject", "ban",
			"frighten", "participate", "compete", "overcome", "arise", "generate", "obtain", "employ", "import",
			"handle", "repair", "cure", "transport", "deliver", "rush", "commit", "hate", "regret", "consist",
			"translate", "conclude", "comfort", "facility", "trait", "humanity", "tribe", "elite", "lawyer", "category",
			"version", "diversity", "proportion", "instrument", "innovation", "weapon", "dialect", "barrier", "myth",
			"ritual", "routine", "emergency", "alarm", "harvest", "grain", "quantity", "budget", "expense", "insurance",
			"loan", "contract", "mammal", "infant", "protein", "tissue", "fault", "neighborhood", "vote", "duty",
			"psychology", "intelligent", "conscious", "cognitive", "sensitive", "accurate", "strict", "severe",
			"actual", "visual", "FALSE", "illegal", "violent", "military", "civil", "typical", "universal", "constant",
			"fundamental", "primary", "rare", "convenient", "enormous", "concentrate", "investigate", "adjust",
			"arrange", "alter", "confirm", "absorb", "expose", "transfer", "abandon", "injure", "recover", "praise",
			"favor", "celebrate", "guarantee", "ensure", "award", "grant", "permit", "disappoint", "embarrass",
			"bother", "upset", "inform", "warn", "command", "imply", "pretend", "interpret", "react", "interact",
			"differ", "breathe", "stare", "breed", "melt", "invest", "manufacture", "construct", "wisdom", "insight",
			"discipline", "habitat", "territory", "colony", "district", "shelter", "landscape", "inhabitant",
			"depression", "nerve", "wound", "symptom", "therapy", "welfare", "incident", "witness", "glance", "ray",
			"ingredient", "agent", "fee", "sacrifice", "burden", "layer", "row", "instruction", "editor", "stuff",
			"mission", "procedure", "immigration", "hybrid", "opponent", "outcome", "equality", "reputation", "capable",
			"proper", "sufficient", "reasonable", "linguistic", "verbal", "bilingual", "contemporary", "conventional",
			"overall", "widespread", "domestic", "distant", "nuclear", "thick", "contrary", "virtual", "aggressive",
			"evil", "elementary", "annual", "immediate", "admire", "approve", "devote", "pursue", "dominate", "possess",
			"occupy", "secure", "capture", "lend", "rent", "persuade", "urge", "stimulate", "annoy", "scare", "crash",
			"collapse", "remark", "illustrate", "protest", "declare", "isolate", "accompany", "surround", "endanger",
			"exhaust", "disturb", "puzzle", "quit", "cope", "enhance", "ease", "apologize", "acknowledge", "resemble",
			"swallow", "distribute", "export", "launch", "justice", "courage", "passion", "bond", "companion", "mood",
			"prejudice", "discrimination", "priority", "globe", "hemisphere", "boundary", "asteroid", "gravity",
			"component", "liquid", "orbit", "trace", "treasure", "logic", "council", "profession", "secretary", "jury",
			"physician", "surgeon", "guard", "license", "grocery", "litter", "drought", "blaze", "trap", "fate",
			"luxury", "exception", "sum", "conservation", "democratic", "numerous", "minor", "superior", "principal",
			"crucial", "vital", "rational", "anxious", "curious", "rude", "remote", "tropical", "marine",
			"extraordinary", "odd", "biological", "racial", "initial", "distinct", "pure", "exact", "sustain", "defend",
			"foster", "pile", "attach", "pour", "load", "stretch", "convey", "derive", "tap", "calculate", "suspect",
			"detect", "attribute", "evaluate", "accuse", "sue", "retire", "shrink", "bow", "peer", "delight", "relieve",
			"discourage", "frustrate", "neglect", "resist", "restrict", "eliminate", "beat", "defeat", "punish",
			"prohibit", "deserve", "pose", "fold", "monitor", "specialize", "accomplish", "faith", "ambition",
			"enthusiasm", "honor", "discount", "fare", "frame", "mode", "architecture", "sequence", "usage", "abuse",
			"pesticide", "pollen", "prefecture", "geography", "administration", "candidate", "rubbish", "bias", "vice",
			"debt", "prospect", "expedition", "session", "semester", "reef", "mineral", "sibling", "proverb",
			"instinct", "minimum", "millennium", "donor", "herd", "league", "cooperation", "fairy", "precise",
			"intense", "solid", "permanent", "brief", "flexible", "informal", "temporary", "frequent", "visible",
			"external", "internal", "plain", "modest", "equivalent", "incredible", "guilty", "raw", "manual",
			"literary", "artificial", "sophisticated", "polish", "embrace", "compose", "imitate", "yield", "exhibit",
			"impress", "overwhelm", "interrupt", "endure", "confront", "consult", "bump", "dispute", "negotiate",
			"justify", "resolve", "reverse", "convert", "impose", "govern", "esteem", "assist", "rescue", "entertain",
			"ruin", "bury", "owe", "chew", "bend", "quote", "classify", "seal", "arrest", "substitute", "retain",
			"restore", "float", "leap", "blossom", "merit", "faculty", "charm", "nutrition", "beverage", "recipe",
			"molecule", "ecology", "ethics", "mankind", "nationality", "pension", "scheme", "haven", "formation",
			"skeleton", "core", "stem", "span", "limitation", "obstacle", "province", "galaxy", "sensation", "sympathy",
			"pity", "tragedy", "divorce", "theft", "panic", "retreat", "jail", "blade", "stroke", "clue", "queue",
			"enterprise", "fortune", "stable", "steady", "mature", "eager", "reluctant", "humorous", "fluent", "prime",
			"precious", "artistic", "ethnic", "primitive", "federal", "royal", "mutual", "apparent", "casual", "slight",
			"mere", "spare", "abstract", "ultimate", "venture", "chase", "migrate", "flee", "swing", "hesitate",
			"postpone", "withdraw", "grip", "grab", "grasp", "gaze", "scan", "forecast", "register", "advocate",
			"trigger", "cultivate", "qualify", "interfere", "clog", "distract", "forbid", "deceive", "overlook",
			"dismiss", "spoil", "yawn", "greet", "nod", "obey", "undergo", "rear", "heal", "cite", "modify",
			"exaggerate", "burst", "thrill", "exceed", "privilege", "liberty", "prosperity", "heritage", "congress",
			"parliament", "infrastructure", "dimension", "portion", "supplement", "appetite", "temper", "fancy",
			"illusion", "fatigue", "stress", "hazard", "infection", "famine", "chaos", "distress", "shame", "cattle",
			"predator", "wilderness", "shade", "monk", "priest", "funeral", "transition", "circulation", "adolescent",
			"equation", "patent", "metaphor", "narrative", "consent", "dignity", "relevant", "adequate", "genuine",
			"prompt", "intimate", "alert", "conservative", "indifferent", "alien", "random", "subtle", "moderate",
			"multiple", "polar", "arctic", "acid", "cosmetic", "extinct", "spiritual", "meaningful", "mechanical",
			"dynamic", "boost", "reinforce", "accumulate", "nurture", "accustom", "correspond", "assign", "regulate",
			"violate", "irritate", "insult", "diminish", "exclude", "rob", "deprive", "deposit", "twist", "blend",
			"mount", "pitch", "cast", "dump", "anticipate", "assess", "pronounce", "spell", "portray", "astonish",
			"emit", "cough", "wander", "drift", "cease", "underlie", "constitute", "resort", "decorate", "reform",
			"conquer", "persist", "incentive", "intuition", "impulse", "fantasy", "destiny", "virtue", "compliment",
			"anniversary", "hive", "nursery", "dormitory", "gallery", "mill", "output", "joint", "phase", "particle",
			"column", "margin", "crack", "mess", "spectator", "prey", "irrigation", "fluid", "prairie", "estate",
			"plot", "realm", "deadline", "poll", "census", "controversy", "combat", "consensus", "treaty", "remedy",
			"triumph", "competent", "brilliant", "sensible", "generous", "brave", "optimistic", "passive", "harsh",
			"ugly", "sensory", "oral", "awkward", "neutral", "vague", "urgent", "inevitable", "concrete", "abundant",
			"sacred", "prominent", "dense", "profound", "tackle", "dedicate", "dare", "accelerate", "transmit",
			"strain", "tempt", "amuse", "disgust", "cheat", "confine", "conceal", "forgive", "discard", "convict",
			"commute", "whisper", "fade", "starve", "vanish", "drain", "dip", "crush", "explode", "terrify", "exploit",
			"elect", "equip", "fulfill", "log", "inherit", "submit", "renew", "reproduce", "flourish", "thrive",
			"spill", "scatter", "sprawl", "prevail", "intellect", "courtesy", "posture", "sociology", "motive", "cue",
			"utility", "chore", "cereal", "fiber", "intake", "scent", "flavor", "mixture", "ratio", "counterpart",
			"patch", "flock", "pedestrian", "librarian", "draft", "formula", "commodity", "asset", "currency", "tide",
			"abortion", "toll", "penalty", "deforestation", "microbe", "outbreak", "epidemic", "syndrome", "outlet",
			"perfume", "reception", "recipient", "keen", "decent", "mild", "humble", "noble", "selfish", "cruel",
			"ridiculous", "deaf", "grateful", "elaborate", "rough", "bitter", "radical", "collective", "exotic",
			"steep", "shallow", "parallel", "probable", "absolute", "aesthetic", "proceed", "bloom", "assert", "bet",
			"boast", "beg", "compromise", "inquire", "yell", "bully", "descend", "crawl", "lean", "spin", "drown",
			"split", "revive", "sigh", "refrain", "sweep", "knit", "cram", "digest", "suppress", "offend", "compensate",
			"compound", "comprise", "transplant", "uncover", "extract", "recruit", "entitle", "appoint", "install",
			"enforce", "implement", "manipulate", "refine", "attain", "quest", "outlook", "premise", "unity", "fabric",
			"thread", "craftsman", "sculpture", "sphere", "curve", "profile", "fingerprint", "criterion", "altitude",
			"tuition", "stake", "acquaintance", "discourse", "gratitude", "worship", "caution", "horror", "decay",
			"defect", "troop", "grave", "ranch", "republic", "county", "cottage", "commerce", "recession", "despair",
			"spray", "compassion", "offspring", "cortex", "fame", "worthwhile", "valid", "thorough", "tremendous",
			"empirical", "secondary", "subsequent", "innate", "interior", "bare", "innocent", "delicate", "ambiguous",
			"fragile", "awful", "inferior", "ashamed", "medieval", "stern", "tense", "imperial", "magnificent",
			"integrate", "incorporate", "utilize", "revise", "prolong", "lessen", "stir", "drag", "scrub", "strip",
			"squeeze", "shed", "plug", "distort", "disrupt", "devastate", "worsen", "abolish", "regain", "exert",
			"precede", "lag", "converse", "utter", "outline", "conform", "designate", "assure", "reassure", "console",
			"induce", "oblige", "compel", "provoke", "bathe", "bleed", "cruise", "soar", "symbolize", "comprehend",
			"protocol", "domain", "index", "transaction", "fragment", "fraction", "bug", "germ", "diagnosis",
			"obsession", "nightmare", "paradox", "irony", "sorrow", "maximum", "excess", "frontier", "refuge", "timber",
			"slavery", "hierarchy", "bureau", "supervisor", "spouse", "rebel", "pastime", "feast", "basin", "sewage",
			"scenery", "tomb", "landmark", "monument", "flesh", "garment", "glimpse", "glow", "grace", "sincere",
			"bold", "tame", "vulnerable", "naked", "immune", "chronic", "gradual", "scarce", "toxic", "accidental",
			"irrelevant", "trivial", "indispensable", "indigenous", "prehistoric", "holy", "retail", "metropolitan",
			"straightforward", "vivid", "outstanding", "enrich", "undertake", "accommodate", "assemble", "embody",
			"weave", "retrieve", "clap", "scratch", "erase", "sew", "cling", "resign", "startle", "evoke", "clarify",
			"confess", "pray", "tolerate", "envy", "revenge", "depart", "overtake", "invade", "penetrate", "enclose",
			"leak", "flush", "sparkle", "erupt", "dye", "halt", "suspend", "surpass", "steer", "navigate", "contradict",
			"contend", "dissolve", "strive", "legacy", "rumor", "verse", "manuscript", "script", "prose", "headline",
			"diameter", "vacuum", "flame", "moisture", "erosion", "peninsula", "suicide", "sin", "taboo", "rage",
			"greed", "boredom", "misery", "plague", "orphan", "liver", "trail", "aisle", "laundry", "merchandise",
			"bargain", "revenue", "deficit", "amateur", "undergraduate", "ambassador", "warrior", "warfare", "botany",
			"anthropology", "ideology", "voluntary", "spontaneous", "deliberate", "conspicuous", "transparent",
			"superficial", "hollow", "peculiar", "partial", "neat", "dim", "alternate", "commonplace", "jealous",
			"hostile", "ripe", "pregnant", "fertile", "fierce", "drastic", "immense", "supreme", "excel", "swell",
			"bounce", "roam", "stray", "emigrate", "mutter", "murmur", "chuckle", "choke", "frown", "roar", "shiver",
			"tremble", "shave", "misunderstand", "soothe", "lure", "mock", "tease", "despise", "disregard", "betray",
			"aspire", "seize", "fetch", "rub", "flap", "plunge", "insert", "dispose", "withstand", "hinder", "resume",
			"unify", "staple", "soybean", "bud", "vegetation", "limb", "wrinkle", "sentiment", "grief", "curse",
			"torture", "mercy", "coward", "predecessor", "psychiatrist", "thesis", "mutation", "diabetes", "bullet",
			"cluster", "shield", "gear", "vessel", "tactics", "breakdown", "reunion", "knot", "probe", "radiation",
			"tablet", "vapor", "thermometer", "signature", "triangle", "geometry", "feat", "applause", "glory",
			"diligent", "earnest", "loyal", "stubborn", "rigid", "stiff", "timid", "idle", "dumb", "obese", "disabled",
			"clumsy", "punctual", "absurd", "uneasy", "nasty", "naughty", "tidy", "decisive", "upright", "vertical",
			"gloomy", "obscure", "antique", "sole", "sheer", "marvelous", "splendid", "cherish", "nourish", "hatch",
			"enlarge", "furnish", "indulge", "surrender", "kneel", "stumble", "wither", "creep", "ache", "await",
			"foresee", "illuminate", "dread", "depict", "signify", "swear", "dictate", "recite", "enroll", "execute",
			"fake", "disguise", "stain", "bind", "slap", "omit", "grind", "undermine", "bankrupt", "extinguish", "mend",
			"congratulate", "certificate", "encyclopedia", "biography", "masterpiece", "rhyme", "means", "mold",
			"scope", "bulk", "trifle", "pill", "dose", "vein", "odor", "pilgrim", "deed", "carriage", "mischief",
			"slaughter", "haste", "thirst", "monarchy", "reign", "heir", "pardon", "legislation", "cabinet", "ward",
			"surplus", "arithmetic", "mercury", "monopoly", "friction", "collision", "fusion", "breakthrough",
			"spectacle", "eminent", "notable", "notorious", "compulsory", "liable", "inclined", "static", "infinite",
			"eternal", "acute", "abrupt", "swift", "faint", "tender", "humid", "damp", "rotten", "sour", "sore",
			"savage", "crude", "approximate", "intermediate", "vocational", "masculine", "feminine", "superfluous",
			"utmost", "contemplate", "ponder", "meditate", "conceive", "speculate", "presume", "proclaim", "disclose",
			"pledge", "exclaim", "subscribe", "mourn", "resent", "lament", "pant", "suck", "soak", "render", "rotate",
			"pierce", "carve", "divert", "expel", "assault", "intrude", "addict", "coincide", "ascend", "surge",
			"evaporate", "expire", "ferment", "merge", "erect", "bless", "prestige", "aristocracy", "statesman",
			"senator", "creed", "vigor", "dismay", "melancholy", "agony", "anguish", "conscience", "contempt", "scorn",
			"apathy", "textile", "symmetry", "verge", "cavity", "bribe", "riot", "exile", "archaeology", "specimen",
			"ornament", "apparatus", "flaw", "eclipse", "astronomy", "aviation", "velocity", "congestion",
			"questionnaire", "parasite", "personnel", "advent", "token", "premium", "discreet", "wary", "grim",
			"solemn", "skeptical", "dubious", "vain", "reckless", "ruthless", "eloquent", "furious", "weary",
			"pessimistic", "cynical", "wicked", "singular", "weird", "literal", "explicit", "implicit", "slender",
			"gross", "ultraviolet", "spatial", "vacant", "spacious", "ample", "affluent", "infer", "discern", "allege",
			"ascribe", "prescribe", "comply", "abide", "plead", "preach", "intrigue", "reconcile", "intervene",
			"restrain", "humiliate", "reproach", "condemn", "defy", "revolt", "impair", "inflict", "degrade",
			"deteriorate", "corrupt", "contaminate", "oppress", "thrust", "embark", "inspect", "summon", "testify",
			"persecute", "coerce", "unleash", "emancipate", "endow", "scrutiny", "analogy", "preoccupation",
			"retrospect", "conceit", "fallacy", "hypocrisy", "nuisance", "delinquency", "hostage", "lawsuit",
			"attorney", "warrant", "testimony", "verdict", "sanction", "superstition", "folklore", "anecdote",
			"rhetoric", "stall", "segment", "synthesis", "cohesion", "heredity", "catastrophe", "plight", "solitude",
			"ordeal", "tyranny", "censorship", "hygiene", "doctrine", "diplomacy", "entity", "sovereign", "authentic",
			"legitimate", "intelligible", "inherent", "ingenious", "intricate", "homogeneous", "monotonous",
			"incessant", "perpetual", "imminent", "plausible", "arbitrary", "preliminary", "deficient", "subordinate",
			"feudal", "obsolete", "mortal", "monetary", "extravagant", "dizzy", "juvenile", "anonymous", "compatible",
			"ubiquitous", "divine", "sober", "zealous"
	};

	// 意味
	public static String[] meanings = { "", "を向上させる?��よくな�?", "を�?...と?��関連づける?�?to?��；�?...に?��関連する?�?to?�?", "を供給する?��≒supply?�?",
			"を見なす；につ�?て�?える", "を含�??��⇔exclude を除外する�?", "?��受身形で?���?...を）�?配する�?about?��；（受身形で?���?...に?��関係する�?with?��；に関連する", "を関与させる?��を伴�?",
			"を生産する?��を取り出�?", "を許す；を与える；�?...を）�??慮に入れる?�?for?�?", "を要求する；を�?要とする", "...のように見える；現れる", "傾向がある?��を世話する",
			"意見が�?致する?��同意す�?", "につ�?て述べ�?", "を�?...に?��加える?�?to?�?", "頼る�?...次第である", "を励ます（⇔discourage に�?る気をなくさせる?�?", "存在する?��生存す�?",
			"を減らす；を?�?...に?��変える�?to?�?", "適応する；を?�?...に?��適�? させる�?to?�?", "を比�?する?��を?�?...に?��例える�?to?�?", "増加する?��⇔decrease 減少する）；を増や�?",
			"を提案する；を暗示する", "?��費用?��がかかる；を�?牲にさせ�?", "を�?�有する；を�?�?する", "かなと思う?���?...に?��驚�?する?�?at?�?", "と主張する?��≒claim?��maintain?��；議論す�?",
			"に気づく；を実現する", "を管�?する?��を制御する", "に影響を及ぼす（≒influence?��；を感動させ�?", "とわかる；を見つける", "に気づ�?", "を避ける", "に強�?る；を強要す�?",
			"を提供す る，申し�?��?", "を要求す�?", "と主張する?��を自�?のも�?��?と主張する", "?�?deal withで?��を処�?する", "を保存する�? を蓄える", "を完�?�させる",
			"価値?��価格?��評価?��（～s?��価値観", "利益，恩恵?��給付��", "機会（≒chance?�?", "質?�? ⇔quantity 量）；特質", "著�???��張本人", "科学�?術；応用�?�?",
			"環�?��≒surroundings?�?", "?�?...につ�?ての?��見解?�?on / about?��；眺�?", "状�?��（人の置かれた）立�?�", "?�?...に対する?��影響?��効果�?on / upon?��；結果",
			"?�?...に対する ?��影響?��力?���?on?�?", "?��専門?��用語；（～s?��条件?��（～s?��間�?��学�?", "�?能?���?�練", "�?論，学説?��原�??��推測", "問題（点?��；発行（物?��；発表", "話題；学科；主題；被験�??",
			"記事；条�??��品物", "主張?��声明；�?�細書", "?�?...を使っ ての?��実験�?with?�?", "数字；姿?��人物?��図?��表?�?", "証�?", "産業?��勤勉（≒diligence?�?", "経済；�?�?",
			"医薬?��≒medication?��；医学", "問題；（～s?��事�?�；�?the ?��）困難?��物質", "材料?���?料；生地", "?��生物の?��種?��種�?", "?��社会�?�?���?�習；実践?��練�?", "焦点?��関�?の�?",
			"記�?�?��力?��；�?...の?���?�い出?�?of?�?", "権利?��右?��正しいこと", "�?致?��合 意，協�?", "�?え；�?��??", "?�?...に対する?���?�味?�?in?��；利子；利害", "説明；勘定；口座",
			"原因?��⇔effect 結果?��；理由?��大義", "音?��響き，印象", "個人", "確信して?��確かな?��ある；�?定�?�", "可能な?��可能性のある", "ありそうな?��⇔unlikely ありそうもな�?�?",
			"手に入る；利用できる?��手が空�?て�?�?", "社会的な?��社交の", "公の?��⇔private 私的な?�? ?���?�開�?�", "身体�?�?��物質�?な?��物�?学の", "科学�?な?��（�?�然?��科学の", "普通�?�?���?�通�?�?���?般の",
			"全般�?な?���?般�?な", "特定�?�?��特別の?���?...につ�?て?��やかましい?�?about?�?", "似て�?る；同様�?�", "さまざまな?��いくつか�?�", "出生地の?��原産の?��生得�?�", "忍�?�強�?��勤勉な", "�?近�?�",
			"...さえ?��（比�?級�?�前で?��いっそう", "?��文頭で?��それでも；�? 否定文で?��ま�??��（疑問文で?��も�?", "かなり；�?しろ?��それどころ�?", "そ�?�代わりに?��そ�?ではなくて",
			"?�?...と?��同�? に?�?with?��；�?斉に", "それぞれ?��どれもこれ�?", "に異議を唱える?��（人?��に挑�?", "を決定する；を正確に知�?", "をど�?にか�?�し遂げる；を管�?する", "を維持する；と主張する",
			"�?及する；関連する?��参照する", "に近づく；に取り�?�?", "進歩する?���?��??��を進める", "を表現する", "を�?める?���?がる", "起こる?���?に浮か�?�?��現れる", "に気づく；を観察する；を遵守す�?",
			"を識別できる?��を認め�?", "と思う?��と仮定す�?", "を見なす；を見る?��を評価する", "を扱�??��を治療す�?", "捜す?��を捜索する?��を詳しく調べ�?", "を証明する；わかる?��判明す�?",
			"を設立する；を確立す�?", "に�?及する；と�?�?", "を表す；を代表する", "の方を好�?", "申し込�??���?...に?��適用される�?to / in?��；を?�?...に?��適用?��応用?�� する?�?to?�?",
			"を追�?求める；（助けなど?��を要請す�?", "を�?�版する；を公表する", "を行う?��を演じる，演奏す�?", "を獲得する；（を?��増す",
			"?��に?��適合する；を?�?...に?���?�め込�??�?in / into?��；を?�?...に?��合わせる�?to?�?", "を含�??���?��? 容能力がある?��を抑え�?", "を供給する",
			"を準備する?��を調�?する?���?...のために?��準備をする�?for?�?", "に耐える（≒stand?��endure?��；を�?�??��を産�??��を運�?�", "を妨げる?��を防�?", "?�?...に?��反対する?�?to?�?",
			"衰�?する?��減少する；を断�?", "に取って代わる?��を取り替える", "をつなぐ；を?�?...と?��関連づける?�?with?�?", "に出席する?��（�?�?��世話をする；�?...に?��精を�?�す�?to?�?",
			"生き延びる；を�?り抜けて?��生き）残る?��より長生きする", "を尊敬する?��を尊重する", "を浪費する", "利点?��⇔disadvantage 不利な点?��；優勢?��有利?���?",
			"?���?��? ?��s?���?源；（�?��? ?��s?���?金；才�?", "?��情報伝達の?�? 媒体；手段", "方法；体系?��秩�?", "?�?...に対する?���??え方?�?toward / to?��；�?�度", "構�???��体系?��構�??物", "機�?�?��関数",
			"特徴?��（～s?��顔つき；特�?記事［番�?��", "?��物事�?�?���?�面?��観点?��様相", "�?容?��中身?��コン�?ン�?", "?��～s?��詳細?��な�?報?��，細部", "�?囲?���?程距離?��並び", "地域；�?�域?��部�?",
			"貿易；商売?��取�?", "習�?�?��癖", "細胞；小�?�室?��電�?", "�?料；勢�?を増加させるもの", "請求書?���?�英】勘定書?��≒【米】check?��；法�?", "料��?��世話?��管�??��告発",
			" ?�?...に対する?��罰金�?for?�?", "温度?��体温?���?�", "10年�?", "感情?��情動；感�?", "説明；解釈；理由", "解決?��策）；溶液", "程度?��度?��学位；等�?", "接近，利用?���?�機会�?",
			"?�?...との?��対照?�?with / to?�?", "地位；状�?", "表面?��外�?", "争い?��論争；不�?致", "?��集合的に?���?��??��視�?��?", "粘土", "時代?��画期的な出来�?", "利益；収益（率?��；�?",
			"収�?�", "先祖（⇔descendant 子孫?��；�?��?�??��原�?", "?��しばし�?� ?��s?��作物?��収穫�?", "重要な?��意義深�?", "�?�? な?��≒essential?�?", "?�?...に?��適�?な?�?for / to?�?",
			"正しい?��適�?な", "の価値がある；（～する）に値する?�?doing?�?", "積極�?な?��肯定的な?���?�確な?��確信して", "柔軟な?���?�ラスチックの?��ビニ�?�ルの", "政治?��上）�?�", "公式�?�?���?�用の?�? 役�?の",
			"私的な?��⇔public 公の?��；民営の", "古代の?���?�から�?�", "?��支払）期日で?��予定された?��しかるべ�?", "�?�? な?���?合（体）�?�", "可動［移動］式�?�?��流動性のある",
			"空白の?��無表�?な?��がらんとした", "男性の?��⇔female 女性の?�? ?��男らし�?", "それ�?えに", "したがって?��このように?��次のように", "結�??���?�?�?", "さもなければ?��その他�?�点では?��違った風に",
			"...にもかかわらず?��≒in spite of?�?", "両方とも；両方の", "?�?...に?���?�功する?�?in?��；�?...を）継承する?�?to?�?", "を特定する；を?�?...と?��同�?視する�?with?�?",
			"を反�?する?��（を?��反�?する?��（を?���?��??する", "を当然のことと 思う?��を手に入れる?��を引き受け�?", "と推定する；を見積もる；を評価する", "を定義する?��を規定す�?", "を指し示す；を述べ�?",
			"を�?�らかにする?��を見せ�?", "を試みる，企て�?", "反応する；答え�?", "を結�?�付けて�?える?���?...と?��交�? する?�?with?�?", "を調べる；を診察する；を尋問する",
			"?��問題など?��を扱�??��に演説する?��（手紙など?��を?�?...あてに?���?��? ?�?to?�?", "を信頼する?��を託す�?", "を疑�??���?...では?��な�?と思う?�?that�??�?", "を無視す�?", "を拒�??��を断�?",
			" ?��と?��不平?��苦�??��を�?�??��訴える", "減少する（⇔increase 増加する?��；を減ら�?", "さまざまである", "現れる?���?�ら�? になる；台頭する", "と合う?��に匹敵する",
			"を動けなくさせる?���?...に?��くっつく�?to / on?�?", "を隠す（≒conceal?���? �?れる", "を引きつける", "を�?進する?��（受身形で?���??進する", "を�?足させる；を�?たす",
			"を稼ぐ；を得る?��をもたらす", "を保持する?��を守る?��を保存す�?", "?��人?��にとって?��～する�?�を）可能にする?�?to do?�?", "を�?�壊する；（人?��を破 �?させ�?", "を引き裂く?��裂け�?",
			"苦し�??��患�??��（苦痛など?��を経験す�?", "を調査する?��を概観する", "を�?ける?���?かれ�?", "を実施する", "?�?...を）卒業する?�?from?�?", "�?与［貢献?��する?��（を?���?付する；（を?���?稿する",
			"を強�? 望�?", "くつろぐ?��緩�??��をくつろがせる?��を緩める", "?��到達）目標；的", "目�?", "主義?��信条?��原�?��原�?", "規�?��標�?", "戦略", "跡?��軌道?���?�米】（鉄道�?�?��番線；走路",
			"進歩?��前進", "個�?�?���?�格", "?��しばし�?� ?��s?��特徴", "方法；物腰?��（～s?��作�?", "�?置?��機器?��方�?", "起源；�?", "遺伝�?", "大気；雰囲�?", "傾向；流�?", "現象",
			"状�?��背景?��文�?", "?���?��? ?��s?��状�?��事情?���?�?", "苦痛；苦悩?��（～s?��骨折り", "闘い?���?�命の努�?", "汚染", "�?�?���??し，恐れ；脅迫", "災害?��惨�?", "?���?��? ?��s?��結果?��重大性",
			"革命?��回転?��（天体�?�?���?�転?��⇔rotation 自転 ?�?", "大部�??��多数派?��⇔minority 少数派?�?", "かたまり；大量；�?般大�?", "在庫�?��蓄え；�?�", "富；�?源；富裕（状 態�?",
			"�?学?��文献?��印刷物", "?�?the ?��ties?��（関係）当�??��権�?��権�?", "機関?��協会；施設?��制度", "?��社会的な?���?�習；（～s?��税関?��（～s?��関�?",
			"光景?���?the ?��s?��名�??��目にすること?��視野?��視力", "?��感�?などの?��表れ；展示?���?示", "?���?�場の?��同僚（≒coworker?�?", "�?住�??", "乗り物?��車；伝達手段?��媒�?",
			"?�?...に?���?要不可�?な?�?to?��；本質�?な", "気づ�?て", "精神�?�?��知能の", "学問�?�?��大学の", "並の?��普通�?�?��常勤の", "精通して�?る；よく知られて�?�?", "目新しい?��斬新な",
			"特定�?�?���?�確な?���?�体的な?���?...に?��特有�?�?�?to?�?", "化学の?��化学�?な", "財政?��上）�?�?��財界�?�", "活動的な?��効力�?�ある?��積極�?な",
			"否定�?�?��⇔affirmative 肯定�?�?��；消極�?な?��⇔positive 積極�?な?��；�?の", "直接の?��⇔indirect 間接の?��；率直な", "明らかな?��≒clear?�?", "現在の?��現代の?���?�用して�?�?",
			"都市�?�?���?�会的な?��⇔rural 田舎�?�?�?", "さらに", "同様に?��≒in the same way?�?", "?��文中?��文末で?��けれど", "それにもかかわらず?��≒nonetheless?�?", "それによって",
			"それ�?えに?��≒therefore?�?", "を正当に評価する?��を鑑賞する；を感謝す�?", "?��を?��認める；に ?�?...への?���?�場?��入学など?��を認める�?to / into?�?", "を予�??��予測?��する",
			"を得る?��を習得す�?", "を採用する?��（�?�度など?��をとる；を養子にする", "を購入する", "を持つ?��する?��余裕がある?��を与え�?", "を消費する?��を食べる，飲�?", "を取り除く；を解�?する",
			"に適する?��に似合う?��を適合させる", "?��を?��拡大する?��（を?��詳説する", "を伸ばす，延ばす；伸びる；及ぶ", "?��を?��調査する?��（を?��探検す�?", "?��を?��判断する?��に判決を下す",
			"を論証?��証明］する?��デモをす�?", "?��を?��強く主張する", "訴える?��抗議する?��上訴する", "を納得［確信?��させ�?", "を解決する?��（に?��移り住�?", "を援助する?��助ける",
			"を教育する?��に教える；（�?�力など?��を養う", "を従事させる?��を?�?...として?��雇�??�?as?��；�?...に?��従事する�?in / with?�?", "を結�?�付ける；�?...と?��結�?�付く?�?with?�?",
			"を�?織する；を準備する", "を操作する；機�?�する?��手術す�?", "を�?�い出す；を呼び戻�?", "頼る（≒depend?�?", "を�?�っくりさせ�?", "を混同する；を当惑させ�?", "を責める?���?�責任を�?わせ�?",
			"を批判する?��を批評す�?", "振る�?�う?��作用する", "に遭�?する?��に?���?�いがけず）�?�会う", "を選ぶ?��精選する", "流れる；�?...から?��生じる?�?from?�?", "?��徐�??に?��発展する；�?�化す�?",
			"凍る?���?�度を硬くする；を 凍らせる", "を放出する?��を解放する?��を発表する", "の位置を探し当てる；（受身形で?��位置する", "を宣伝する；�?...�? 求める）�?告を出す�?for?�?", "想像（力?�?",
			"観点?��大�?観?��遠近�?", "自信?��信頼?��秘�?", "業績?��達成，�?�就", "報 酬?���?��?", "?��大?��企業?��法人", "�?本?��首�?�?��大�?字（＝capital letter?�?",
			"顧客?��≒customer?��；（弁護士などの?��依�?�人", "危�?", "害", "�?牲?���???��，被害�?", "選択（�?�自由?��；選択肢", "運動?��軍事行動", "裁判�??��法廷?��裁判?��宮廷?��中庭",
			"規�?��暗号?��符号?��法�?�", "犯罪�??��犯人", "農業?��農学?��畜産", "宗教?��信条?��信仰?���?�?", "哲学?��原�??��人生観", "会議?��協議", "?���?�?��文書?��記録?���?�?", "統計；統計学", "�?析（結果?�?",
			"仮説?���?�測", "概念?��観念?��見解?��意�?", "固定観念?��決まり文句", "?��書物などの?��論評；�?�調査?���?�米】復�?", "語�?", "臓器?���?�?", "?��社会的・�?化的?���?�別", "化石?��時代�?れ�?�人?��物?��",
			"氷河", "実験室?���?�究室", "ウイルス?��（感染症の?��病原�?", "場合，時?��行事；機�?", "大臣?��（�?�ロ�?スタント系の?��聖職�?", "存在?���?�席?��面�?", "物質?��実質?��趣旨",
			"創�?�?な?��独創�?な?��創�?力�?�ある", "潜在�?な?��可能性を秘め�?", "?�?...から?��独立した�?of / from?�?", "�?とわな�?", "効�?�?な?��有能な", "�?想�?な?��観念�?な",
			"遺伝（子）�?�?��発生�?�", "全体�?�?���?�部の?��≒whole?��；完�?�な", "相対�?な?��⇔absolute 絶対�?な?��；比�?上�?�?���?...と?��関連した?�?to?�?", "極端な?��極度の?��過�?な", "�?大な?��莫大な",
			"とても小さな?��わずか な", "人の住まな�?���?��?の?��よ�?な?�?", "田舎�?�?��⇔urban 都会�?�?�?", "以前�?�?��前の", "法律�?�?��合法�?�?��⇔illegal 違法�?�?�?",
			"近ごろ�?�?��≒these days?��today?�?", "めったに...な�?��≒rarely?�?", "?�?2つの事柄を対比して?���?方?��その�?", "?�?the ?��）（二�??の�?ちの?��後�???��⇔the former 前�???�?",
			"?�?A versus Bで?��A対B?��AかB�?", "すべて?���?�も�?�?��；�?��?", "を知覚す�?", "を予期する?��を期�?する", "を意図する", "を要請する；に?��～するよ�?に?���?��??�?to do?�?",
			"に思い出 させ�?", "?��人?��を触発する?��を喚起する", "を�?�?する", "を強調する?��を重視す�?", "を勧める", "を提案する；をもくろ�??��結婚を申し込�?", "を区別する", "を�?雑にする",
			"を変える；変わ�?", "?��功績など?��を?�?...に?��帰する?�?to?�? ?��を信じる", "?��判断など?��を保留する?��を予�?する?��を取っておく", "に反対する?��を対抗［対比］させ�?", "を否定する；を拒�?",
			"を拒否する", "を（法的に?��禁止する?��を�?め�?��?", "?��人?��を怖がらせ�?", "参加する", "競�??��匹敵する", "を�?�服する", "生じ�?", "を生み出�?", "を得る", "を雇�??��を使�?",
			"を輸入する?��⇔export を輸出する?��；を�? り�?�れる", "を�?��?する?��を論じる；を�?�?", "を修�?する?��≒fix?��；を修復する", "を治す；を除去する?��（病気が?��治�?", "を輸送す�?",
			"を�?�達する?��（演説・講義?��をする?��子を産�?", "急�?で行く?���?�急に行動する?��をせき立て�?", "?�?commit oneself また�?�受身形で?��深くかかわる；（罪など?��を犯�?", "を�?�どく嫌う?��を残念に思う",
			"を後悔する", "?�?...�? ら）�?�る?�?of?��；�?...に?��ある�?in?�?", "を翻訳する?��を?�?...に?��変える�?into?�?", "と結論づける?��を�?めくくる?��を�?結す�?", "快適さ；�?��?",
			"施設?��設備；機�?�?��才能", "特性?��≒feature?�?", "人類；人間�?�?��人�?", "部�?", "?���?��? the ?��）（集合的に?��エリー�?", "弁護士", "部類；区�?", "?��本・製品などの?��版?��解�?",
			"多様�?�?��相違点", "割合；部�??���?�り合�?", "器具?��楽器?��＝musical instrument?�?", "革新?��新機軸", "兵器?��武器", "方�?",
			"?�?...に対する?��障 �?�?against / to?��；防�?���?界�?", "作り話?��神話", "�?式；（日常の?��習�?��?行為", "決まり�??った仕事；いつも�?�手�??", "緊�?�?��事�?��?", "不安；警報",
			"収穫?��物?��；漁獲�?", "�?物?��粒；き�?", "量（⇔quality 質?�?", "予算；経費", "?��～s?��経費?��費用?��犠牲", "保険?��保険料；保険�?", "貸付��?��融�?��貸し付け", "契�?��書?��；協�?",
			"哺乳動物", "乳児；幼�?", "たんぱく質", "?��生物の?���?織；ティ�?シュペ�?�パ�?�", "?���?��? one's ?��）責任?���?点?��誤�?", "地域；近所", "投票?��投票結果?���?the ?��）選挙権",
			"義務；�?�務；関�?", "�?�?学", "聡明な?��知能を有する", "意識して?��気づ�?て?��≒aware?�?", "認知の", "敏感な?��神経質な?��微妙な", "正確な?��精�?な", "厳格な?��（規則などが）厳しい",
			"?�? 人・規律などが）厳しい?��猛烈な", "実際の", "視覚�?�?��目に見え�?", "誤った；うそ�?�?��偽の", "違法�?�?��不法�?�?��⇔legal 合法�?�?�?", "暴力的な?��（人・気質が）�?しい", "軍�?�",
			"市民�?�?��民間の?��民事�?�?��⇔criminal 刑事�?�?�?", "典型的な ?���?...に?��特有�?�?�?of?�?", "普遍的な?���?宙�?�?���?能の", "絶え間な�?���?定�?�", "基本�?な?���?須�?�",
			"�?も重要な?��第 �?の?���?�等（教育?���?�", "珍し�?��希少な", "便利な?���?�合�?��?�?", "巨大な?��莫大な", "?��を?��集中する", "を調査する?��を究明する；�?...を）調査する?�?into?�?",
			"を調整する?��を適合させる?���??応す�?", "の段取りをつける?��を手�?�する；を�? 置する", "を変える；変わる（≒change?�?", "を確認す�?", "を吸収する；を併合す�?",
			"をさらす?��を暴露する?��を露出する", "を移す；を伝える；移る；乗り換え�?", "を捨てる；を放�?する", "を傷つける?��を損な�??��≒hurt?�?", "回復する?��を取り戻�?",
			"を�?...のことで?��賞賛する�?for?��；賛美す�?", "に賛�?�する；を好�??��をひ�?きす�?", "を祝う?��を挙行す�?", "を保証する", "を確実にする?��≒make sure?��；を守る",
			"を授与する；を裁定す�?", "を与える；を認め�?", "を許 可する?��≒allow?�?", "を失望させる?��（希望など?��をくじ�?", "に恥ずかしい思いをさせる",
			"を悩ます；�?...を）気にかける�?about / with?�?", "を動揺させる；を�?めにする", "に知らせる；情報を提供す�?", "?��人?��に?�?...につ�?て?��警告す�? ?�?of / against?�?",
			"と命じる?��を�?揮する?��を支配する；（景色?��を見渡せる?��を操る", "を暗に意味する?��を�?然�?に伴�?", "のふりをする", "を解釈する；（を?���?�訳する", "反応する；化学反応を起こす",
			"影響し合�??��相互に作用する", "異な�?", "呼吸する?��を吸�?", "?��を?��じっと見る", "を飼育する?��繁殖させる?��繁殖する；生じる", "溶ける?��なご�??��を溶かす",
			"?��を?��投�?する?��に?�?...を）与える�?with?�?", "を製�?する?��をでっち上げ�?", "を建設する?��を構�?�す�?", "知 恵?��学�?", "洞察力?��見�?", "規律，しつけ；訓練?���?�戒；学問�?�?",
			"生�?�地?��（人の?���?住地", "領土?��（活動などの?���?�域", "植民地?���?留地?��（動植物の?��コロニ�?�", "地区?��行政区", "避難?��所?��，保護", "風景?���?�域", "住民；生息動物",
			"憂うつ?��うつ�??��不�?��低気圧", "神経；（～s?��神経過敏；（～する）度胸?�?to do?�?", "?��銃弾・�?物などによる?��傷?��痛�?", "�?状?���??候（≒sign?�?", "療法；�?�?療�?", "福祉，幸�?",
			"出来事，事件?��紛�?", "目�?�??��≒eyewitness?��；証人?��証�??��証�?", "?�?...を）ちらっと見ること?�?at?�?", "光�?", "成�??��材料；要�?", "仲介�???��代�?人?��薬剤", " 料��?��謝礼",
			"�?牲?��いけに�?", "�?�??��（重�?��義務；積み荷", "層", "列；（建物が並ぶ?���?�り", "?���?��? ?��s?��指示?��（～s?��（製品�?�?��使用書", "編�?�?", "?���?然と?��物?���?材；�?質",
			"使命?��（外交?��使�?団", "手続き?��（�?連の?��措 置", "?��外国からの?��移住（⇔emigration ?��外国への?��移住）；�?�国管�?事務�??��＝immigration control?�?",
			"ハイブリ�?ド車；（動植物の?��雑種?��混成物", "?��試合�?�論争などの?��相手；反対�?", "結果?��≒result?�?", "平等，対�?", "評判", "能力がある?��有能な",
			"適�?な?��正式�?�?���?...に?��固有�?�?�?to?�?", "?�?...に?��～する�?�に?��十�?な?�?for ?��to do?��（⇔insufficient 十�?でな�?�?", "合理�?な?���?別のある?��（�?�段が）手ごろな", "�?語�?�",
			"�?葉�?�?��口頭での?���?�語的な", "2�?語を 使�?", "現代の?��同時代の?��同年輩の", "従来の?��月並みな", "全体的な", "�?�?囲にわたる；�?く普及し�?", "家庭の?��国�?の?��（動物が）飼�?ならされた",
			"�?�?��隔たっ�?", "核の?��原子力の", "厚い?��⇔thin �?�?��；太�?���?�?", "?�?...と?��反対の?�?to?�?", "仮想の?��事実上�?�", "攻�?�?な?��意欲�?な", "邪悪な?��有害な", "初級�?�?��基本�?な",
			"1年間�?�?�? 年1回�?�?��例年の", "即座の?��当面の?��すぐそばの?��直接の", "に?�?...のことで?��感�?する?�?for?�?", "賛�?�する；を承認す�?", "をささげ�?", "を追求する；に従事す�?",
			"を支配する；�?...より?��優勢である?�?over?�?", "を所有して�?る；�?��?をとらえ�?", "?��空間�?�時間?��を�?める?��を�?領す�?", "を確保する；を守る", "を捕らえる；を引きつける",
			"を貸す（⇔borrow を�?�りる）；（人?��に?��物?��を与え�?", "を�?借りする?��を�?貸しす�?", "を説得する；に確信させ�?", "に�?す；を強�? 主張する?��を追�?立て�?", "を刺�?する",
			"を悩ます；（受身形で?���?�が立つ", "をおびえさせる?��を�?�?", "衝突する，墜落する?��をぶつけて壊す", "崩壊する；（人が）�?�れる；を折り畳�?",
			"と述べる；�?...につ�?て?��意見を述べる�?on / upon?�?", "を説明する；に挿絵を�?�れる", "抗議する?��を主張する", "を宣�?する?��を申告す�?", "を孤立させる", "に同行する；に付随する",
			"を取り巻く；にまつわる", "を危険にさら�?", "を疲れ果てさせる；を使�?尽くす?��排気す�?", "をかき乱す；を邪魔する；を不安にする", "を当惑させ�?", "をやめる?��（�?��??��を去�?", "�?まく�?��?する",
			"?��価値など?��を高め�?", "を軽減する；和らぐ?��緩�?", "?�?...に?�?...のことで?��謝る?�?to?��for?��；弁�?�す�?", "を認める（≒admit?��；に謝意を表�?", "に似て�?�?",
			"?��を?��飲み込�??��を�?のみにする?��に耐え�?", "を�?配する；（受身形で?���?�?する", "?��を?��輸出する?��⇔import 輸入する?�?", "を開始する；を売り�?�す；を発�?する", "公正?��正義?��司�?", "�?�?",
			"�?熱?���?�中?���?�?", "�??��債券?��束縛；接�?剤", "連れ；仲�?", "気�??��機嫌；雰囲�?", "?�?...に対する?��偏見�?against?��（≒bias?�?", " ?�?...に対する?��差別?�?against?��；区別",
			"優先（事�???�?", "地�?��≒earth?��；世界?��球", "半球", "�?界（線）；（�?��? ?��ies?��限�?", "小惑星（≒minor planet?��；ヒトデ", "重力?��引力?��重量；重大�?", "構�?�要�??��部�?",
			"液�?", "軌道 ?���?囲", "痕跡?��微�?", "宝物?��財産", "論理?��道�??��原�?", "?��地方?��議会；評議会；（�?�の?��会議", "職業?��専門職?��同業�?仲�?", "秘書?��事務官；�?�米】長�?",
			"陪審?��員団?��；審査員団", "�?科医", "外科医?��軍医", "護衛�???��監視，警�?", "免許?��証?�?", "?��～ies?��食料雑貨?��食料雑貨�?", "ごみ?��乱雑な状�?", "干ばつ?��（�?�性�?な?��不足",
			"炎；強�? 輝き", "わな?��苦�?", "運命?��結末?��最�?", "ぜいたく?��品?��；（形容詞的に?��豪華な", "?�?...の?��例外�?to?�?", "金�? ?��合計；要点", "?��動植物などの?��保護?��保�?",
			"民主主義の?��民主�?な", "非常に数の多い", "小さ�?��⇔major 大きい方の?��；重要でな�?", "よりすぐれた?��⇔inferior より劣った�?", "主要な?���?本金�?�", "重要な?��厳しい",
			"�?要不可�?な ?��生き生きした；生命にかかわる", "�?性�?な?��合�?�?な?��⇔irrational 不合�?な?�?", "�?配して?���??望して", "好�?�?の強 �?���?妙な",
			"無礼な?��⇔polite 礼�?正しい?��；粗野な", "?�?...から?��遠く離れた?�?from?��；かけ離れた", "熱帯の", "海の?��船舶の", "異常な?��⇔ordinary 普通�?�?��；並はずれ�?",
			"�?妙な?��≒strange?��；�?数の", "生物学?��上）�?�", "人種の?��民族の", "初めの", "明らかに異なる；�?�瞭な", "純粋な?��潔白な?���?�く�?�", "正確な?��まさにそ�?�", "を持続させる?��を支える",
			"を防御する?��を弁護する", "を�?進する?��を養育する?��を�?に抱�?", "を積み重�?�る；積み重な�?", "を付ける；を付与す�?", "を注ぐ；（を?��放出する?���?しく降る?��押し�?せる", "に積�??��に�?わせ�?",
			"を伸ばす；を�?げる?��伸びる；及ぶ", "を伝える；を運�?�", "由来する?��を引き出す；を推論す�?", "?��を?��有効利用する?��を引き出す；を軽くたたく", "を計算する；を予測する",
			"ではな�?かと思う?��（人?��を疑う", "を感知する?��を見つけ�?��?", "?��結果など?��を?�?...に?�? 帰する?�?to?�?", "を評価する?��を査定す�?", "を非難する?��を告訴する",
			"を告訴する?���?...を求めて?��訴訟を起こす?�?for?�?", "?�?...から?��引�??する?���??職する?�?from?�?", "縮�??��減少する；�?�る�?", "おじぎする；屈服する",
			"?�?...を）じっと見る?�?at / into?�?", "を喜ばせる?���?...を）大�?に喜�?�?�?in?�?", "を和らげる；（受身形で?��（～して?��安�?する?�?to do?��；を 解放する",
			"?��人?��に�?る気をなくさせる?��を落�?させる（⇔encourage を励ます�?", "を挫折させる?��（受身形で?���?...に?�? 不�?を抱く�?with?�?", "を�??る；を無視す�?", "に抵抗する；（否定文で?��に耐え�?",
			"を制限す�?", "を取り除�?", "?��を?��打つ?��を打ち�?かす", "を�?かす?��≒beat?��；を失敗させる", "を罰する?��に損傷を与え�?", "を禁止する", "に値する",
			"?��問題など?��を提起する?���?��?�ズをとる；�?...を）�?�??�?as?�?", "を折り畳�??��畳める?��（�?�など?��を�?�?", "を監視す る；を傍受する",
			"専門とする?���?�英】�?...を）専攻する?�?in?��（≒【米】major?�?", "を�?�し遂げ�?", "?�?...への?��信頼?�?in?��；信仰?���?�?", "?�?...への?��野望�?of / for?��；野�?",
			"?�?...への?���?��??�?for?�?", "光�??��名誉（⇔dishonor 不名誉�? ?��敬�?", "割�?", "?��乗り物の?��料�?", "�??���?��骨�?み?��体�?�", "方式；気�??��形態；流�?", "建築；建築様式；構�??",
			"�?連?���?�も�?�?��；�?��?", "語法；使用?��法�?", "濫用?��虐�?", "殺虫剤?��除草剤?��≒herbicide?�?", "花�?", "県，�?", "?�?the ?��）地�??��地�?学", "管�??��部?��；行政?��政府（機関?�?",
			"?�?...の?���?�補（�???���?for?��；�?�英】志願�??", "【英 】ごみ?��≒【米】garbage?��；つまらな�?も�?�", "偏見；傾�?", "悪?��⇔virtue 美徳?��；�?点", "借��?��恩義",
			"見込み?��（～s?��展望?��有望な人", "�?�?��隊?�?", "�?まり；（議会�?�?��会期?��（開会中の?��議�?", "学�?", "?��岩�?砂�?�?���?��暗�?", "鉱物?��ミネラル", "きょ�?�?�?", "ことわざ?��≒saying?�?",
			"本能?��（�?�然に起こる?��衝動?��勘", "�?小限度?��⇔maximum �?大限�?", "�?年間，千年�?", "�?贈�???��臓器?���?液?��提供�??", "?��牛などの?��群れ；群�?", "?��競�??���?�盟；同�?", " 協力",
			"妖精の?��よ�?な?�?", "正確な?��≒exact?��；精�?な?��まさにそ�?�", "強烈な?���?�烈な", "固体�?�?���?�丈な", "永�? �?な?��⇔temporary �?時的な?�?", "短�?��簡潔な", "融�?��?�利く，柔軟な",
			"形式�?�らな�?��略式�?�?��⇔formal 正式�?�?�?", "�?時的な?��⇔permanent 永続的な?�?", "頻繁な", "?��目に?��見える（⇔invisible 見えな�?��；�?�白な",
			"外部の?��⇔internal �?部の?��；対外的な?��表面�?な", "�?部の?��⇔external 外部の?��；国�?の?���??面�?な", "明らかな?��平易な?��率直な", "�? 虚な?��≒humble?��；適度な?��質�?な",
			"等し�?��相当す�?", "信じられな�?��すばらし�?", "罪悪感�?�ある?���?...につ�?て?�? 有罪の?�?of?�?", "生�?�?��未�?工の", "体を使�??��手の?��手動式�?�",
			"�?学の?��文語�?�?��⇔colloquial 口語体�?�?�?", "人工の ?��⇔natural 自然の?��；不�?�然な", "洗練された；精巧な", "を磨く；を洗練させ�?", "を受け�?�れる?��（を?��抱擁する；を�?含する",
			"を構�?�する；を創作する；を鎮静す�?", "をまねる；を模�?する", "をもたらす；を産出する?��を?�?...に?��譲る�?to?��；�?...に?��屈する�?to?�?", "を展示する?��（感�?など?��を表�?",
			"を感動させる?��に印象を与え�?", "を圧倒する；を打ちのめす", "を中断させる；（�?�?��邪魔をする", "に耐える（≒put up with?��；存続す�?", "に立ち向か�??��（困難などが）に 立ちは�?かる",
			"?��に?��相�?する?��を参�?�する", "?�?bump into で?��に偶然出会う?��（に?���?�つかる?��をぶつける", "に異議を唱える?��（を?��議論す�?", "交渉する；を?��交渉して?��取り決める", "を正当化する",
			"を解決する?��を決意する；を議決する", "を�??転させる；を反対にする", "を変える；を交換す�?", "を課す；を押し付け�?", "?��を?��支配する；（を?��統治する", "を尊敬する?��を見な�?",
			"?��を?��援助する?��を手伝う", "を救�?", "を楽しませる?��をもてな�?", "をだめにする?��を破�?させる；�?亡する", "を埋める?��を埋葬する?��を�?�?", "に借りがある；�?�おかげである", "?��を?��噛�?",
			"を曲げる?��を屈服させる；曲がる", "を引用する?��を引き合いに出�?", "を�?類する；を機�?扱�?にする", "を�?閉する；に封をする", "を�?�捕する；を止める?��（注意）を引く",
			"を代わりに使�??���?...の?��代�?をする�?for?�?", "を保持する?��を覚えて�?�?", "を回復させる；を修復する", "浮か�?�?��漂う?��を浮かべ�?", "跳ぶ?��さっと動く?���?�上�??する",
			"花が咲く（≒bloom?��；発 展す�?", "利点?��⇔demerit �?点?��；功績?��真価", "能力，機�?�?��学部?��教授陣", "�?力；お守り", "�?養（�?�摂取?�?", "?��水以外�?�?��飲み物?��飲�?",
			"調�?法，レシピ；手�?", "�?子；微粒�?", "生�?�学?��生態系?��環�?保護", "倫�??��道徳", "人�?", "国籍；国民；国民�?�", "年�?", "計画?��≒plan?��；体系?��陰�?", "避難�??��保護区?��港",
			"形成；構�?�物?��隊�?", "骨格?��骨�?み", "核�?��芯", "?��草木の?��茎?��幹", "期間?���?囲", "制限；（�?��? ?��s?��限�?", "?�?...に対する?��障 害?��物?���?to?�?",
			"州，県?���?the ?��s?��地方?���?�?", "星雲?��銀河", "感覚；大評判", "同情?���?...に対する?���?�感�?with / for?�?", "�?れみ?��残念なこと", "悲�?��的な事件?��（⇔comedy 喜劇?�?",
			"離婚；�?離", "�?盗（罪?�?", "狼狽?��パ�? �?ク", "後�???���??却?��引�??", "刑務�??��拘置�?", "�?��（�?�ロペラなどの?��羽根?��（草などの?��葉", "脳卒中?��打つこと?���?�?",
			"?�?...の?��手がかり�?to?��；（パズルの?��ヒン�?", "【英】（�??番を�?つ?���?�（≒【米】line?�?", "企業?��事業?���?�取�?� 気�?�", "財産?��幸運（≒luck?��；運命", "安定した；動じな�?",
			"�?実な?��安定し�?", "成�?�した（⇔immature 未熟な?���? 熟し�?", "?�?...を）�?�望して?�?for?��；�?��?な", "気が進まな�?��嫌がる（⇔willing �?とわな�?�?",
			"ひ�?�?きんな?��ユーモアのある", "流ち�?�?な", "�?も重要な?��第�?の", "貴重な?��高価な?��≒valuable?�?", "芸術的な", "民族の?��人種の?��民族特有�?�", "原始的な?��未開�?�",
			"連邦?��政府）�?�", "王�?�", "相互�?�?���?�通�?�", "明白な?���?�?...らし�?", "何気な �?��形式�?�らな�?", "わずかな?��取るに足らな�?", "単なる，ほん�?�", "余�?の?��予備の",
			"抽象�?な?��⇔concrete 具体的 な?�?", "究極の", "危険を�?�して進�??���?�い�?ってする", "?��を?��追跡する?��（を?��追求す�?", "移住する；（鳥などが）渡�?", "?��から）�??げる",
			"を揺らす?��振る；揺れる?���?変す�?", "躊�?する", "を延期する（≒put off?�?", "を引き出�? ?��を撤回する；撤�?する", "を握る；をとらえ�?", "をつか�??��を横領する；を急�?で食べ�?",
			"を把握する?��をしっかり握�?", "じっと見る", "を注意深く調べる；をざっと見る", "を予想する?��を予�?�する", "を記録する?��登録する?��を示�?", "を主張する?��を擁護する", "を引き起こす",
			"を養う?��を栽培する", "?��人?��に�?格を与える；�?格があ�?", "干渉する，介�?�する?��邪魔す�?", "を詰まらせる；を阻害する?��詰ま�?", "?��注意など?��をそら�?", "を禁じ�?",
			"をだます（≒take in ?�?", "を見落とす；を大目に見る?��を見渡�?", "?��意見など?��を�?ける?��を解�?する", "を台無しにする?��を甘やかす?��だめにな�?", "あくびをす�?", "に挨拶する?��を迎え�?",
			"�?なずく?��うと�?とする", "に従う?��に服従す�?", "を経験する；を受ける；に耐え�?", "?��人・動物・植物?��を育てる（≒raise, breed?�?", "を治す；治�?", "を引き合いに出す；を引用する",
			"を修正する?��を緩和す�?", "?��を?���?張する?��を強調する", "破裂する；�?...を）突然始める�?into?�?", "をぞくぞくさ せる?��わくわくす�?", "を�?える?��に勝る", "特権?��特典",
			"自由?��≒freedom?��；解放?��気まま", "繁�??", "遺産", " ?��米国などの?��議会；会議", "?��英国などの?��議会；国会議員団", "?��経済）基盤?��インフラ", "側面?���?面?��次�?��寸�?",
			"部�??��１人前；割り当て", "�?養補助剤?��補足", "食欲?��欲�?", "気質?��気�?�?��機嫌；かんし�?�?", "?��気まぐれな?��好み?��空想?���?�いつ�?", "錯覚，�?�い違い?��幻想", "疲労?��≒exhaustion?�?",
			"ストレス?��圧力；強調", "危険?��要�??��；�?�然", "感染?��症?�?", "飢饉；（食糧・物�?の?���?�ど�?不足", "混沌，大混乱", "苦悩?��苦痛；困窮", "恥?��残念なこと", "?��集合的に?��牛",
			"捕食動物?��略奪�?", "荒野", "?��日?��陰?���?�暗の度合い?��日よけ", "修道士?��僧?��⇔nun 修道女?��尼?�?", "聖�?��?", "葬�?", "移り変わり；過渡�?", "循環?���?通；（新聞�?�雑誌�?�?��発行部数",
			"青年", "方程式；�?the ?��）同�?�?", "特許?��権?��；特許�?", "�?喩?��比喩", "物語，話", "同意?��承諾", "尊厳?��威厳", "関係がある?��⇔irrelevant 関係�?�な�?��；適�?な",
			"十�?な?��適�?な?��⇔inadequate 不適�?な?�?", "本物の?��≒real, authentic?�?", "�?速な", "親 �?な?���?接な", "警戒して?��敏速な", "保守的な?��保守�?��?�?��控えめな",
			"無関�?な?��≒uninterested?�?", "?�?...にとって ?��異質の?�?to?��；外国の", "無作為の?��手当たり次第の", "微妙な?��希薄な", "適度な?��穏健な", "多様な", "極地の?��電極の",
			"?��しばし�?�A-?��北極の?��⇔antarctic 南極の?�?", "酸性の?���?�っぱ�?��辛辣な", "化粧の?��美容の", "絶�?した?���?止され�?", "精神�?�?��⇔material 物質の?��；霊�?な", "意味のある",
			"機械の?��機械�?な", "活動的な?��動�?な?��⇔static 静的な?�?", "を高める；を増加させ�?", "を強化す�?", "を蓄積する；積も�?", "を�?�ぐく�??��を養�?�す�?", "?��人?��を慣れさせる",
			"�?致する?��文通す�?", "を�?�属する；を割り当て�?", "を規制する?��を調整する", "を侵害する?��（規則?��を破�?", "をいらいらさせる", "を侮辱する?��≒affront?�?",
			"を減らす；減少する（≒decrease?�?", "を除外する（⇔include  を含�??�?", "から?����品を?��奪�?", "から?��権利などを）奪�?", "を置く；を預ける；を�?積させる",
			"を�?�じる?���?�ねる；を歪曲する", "を混ぜる?��を調和させる", "に�?手する；に乗る?��に乗せる；増え�?", "を投げる", "を投じる?��に役を当て�?", "を投�?する?��を落と�?", "を予期する",
			"を評価する?��を査定す�?", "を宣�?する?��を発音する", "?��語）をつづる；と�?�?語にな�?", "を描く；を演じ�?", "を驚か�?", "?���?��?�音など?��を出�?", "咳をす�?", "歩き回る；それる?���?�ぐれ�?",
			"漂う?��さまよう?��を押し流す", "をやめる?��終わ�?", "の根底にある", "を構�?�す�?", "?��好ましくな�?手段に?��訴える", "を�?飾する", "を改革する", "を征服する?��を克服する",
			"固執する?��続く", "動機（付け?��；�?�奨�?", "直観?��力?��，直�?", "衝動?��刺�?", "空想?��幻想?��幻想�?作品", "運命", "美徳?��長�??��効能", "賛辞；表敬", "記念日", "ミツバチの巣?��群�?",
			"託�?�所?��苗�?", "【米】寮", "美術館?��画廊；回�?", "製�?工場?��製粉所?��粉�?�き�?", "生産?��高）；�?�力；排出?��量?�?", "関�??��接合（部?�?", "段階；面", "?��微?��粒子；ほん�?�わず�?",
			"コラ�??��（新聞などの?���?���??柱", "余白?��差?��利ざや", "割れ目?��鋭�?音", "散らかった状態；混乱状�?", "?��試合などの?��観客", "獲物?��犠牲�?", "灌�?", "流動体，液�?", "大草原",
			"?��動産・不動産などの?��財産?��私有地", "?��小説などの?��筋；陰�?", "領域?���?�土", "�?め�??�?", "世論調査?��＝opinion poll?��；投票?��数?�?", "国勢調査?��交通調査", "論�?",
			"戦闘；対�?", "総意?��（意見�?�?���?致", "?��国家間�?�?��条�?��協�?", "治療（法）；治療薬?��解決�?", "勝利?��勝利の喜�?�?��偉業", "有�?�な?��適任の?���?足できる", "す�?�らし�?��才能にあ�?�れた?��きらめ�?",
			"賢明な?��実用�?な?��顕著な", "寛大な?��気前のよい?��⇔stingy けちな?��；豊富な", "�?敢な?��⇔cowardly �?�?な?��；見事な", "楽観�?な?��⇔pessimistic 悲観�?な?�?",
			"受動�?な?��消極�?な", "厳しい?��ざらつ�?�?", "醜い?��険悪な", "感覚�?�", "口頭の", "気まずい?��ぎこちな�?��面倒な", "中立�?�?���?�っきりしな�?", "�?然とした", "緊�?�の", "避けられな�?",
			"具体的な?��⇔abstract 抽象�?な?��；有形の", "豊富な", "神聖な?��≒holy?��；宗教�?な", "卓越した；目立つ", "�?�?した?���?度の高い?��（霧などが）�?�?", "重大な?��深�?��難解 な",
			"に取り�?�??��と話をつける", "をささげる；を献呈す�?", "あえて?��思い�?って?��?��す�?", "?��を?��加速する，�?進する", "を伝える；を送る", "に�?�?をかける?��を緊張させる；を漉す",
			"を引きつける?��（人?��を?��する気にさせ�?", "をおもしろがらせる；を楽しませる", "を�?かつかせる；に愛想を尽かせ�?", "をだます；不正をす�?", "を限定する；（�?�例受身形で?��閉じ込められる",
			"を隠す（≒hide?��；を秘�?にする", "許す；を免除する", "を捨てる；を解�?する", "に有罪を宣告す�?", "通勤?��通学?��する", "?��と?��ささや�?", "�?れる?��衰える",
			"飢える?���?...を）�?望する�?for?��；を飢えさせる", "消える（≒disappear?�?", "?��液体）を流�?�させる；（液体が?��流れ出�?", "を浸す；を突っ込�??��下が�?", "�? 押しつぶす；を弾圧する",
			"�?発する?���?�増する；を論�?�する", "を�?�がらせる；を�?かす", "を活用する?��を搾取す�?", "を選出する", "に備えつける?��を?�?...のために?���?備する�?for?�?", "を実現させる；を果たす；を�?たす",
			"?�?log onで?��ログオンする?��を記録する", "を受け継ぐ?��を引き継ぐ", "を提出する?���?submit oneselfで?��従う?���?...に?��屈服する?�?to?�?", "を更新する?��を再生する",
			"を�?製する?��を再生する?��繁殖す�?", "繁�??する?��繁茂する?��を振りかざす", "繁�??する?���?? 功する；繁茂する", "をこぼす；こぼれる", "をまき散らす?��四散する", "?���?�市などが）不規則に�?がる",
			"普及して�?る；支配的である?��打ち勝つ", "知性?���?the ?��）知識人", "礼�?正しさ?��好意；優�?", "姿勢?���?構え", "社会学", "動�?", "合図?��手掛か�?", "公共事業?��実用性",
			"雑用?��日課?��嫌な仕�?", "?���?��? ?��s?���?物?��シリアル?���?物�?工食品?�?", "繊維?��質?��；本質?��精神力", "摂取量；受け�?�れ数", "香り?��香水?��気�??", "風味?��特色", "混合（物?�?", "比率",
			"相当する物?��人?��", "小区画の土地?��継ぎ?���?�り薬", "群れ；群�?", "歩行�??", "司書?��図書館員", "下書き；為替手形?��すき間風", "方法；�?�式；製�?", "�?�?��有用なも�?�",
			"?���?��? ?��s?���?産?��価値のあるも�?�?��利点", "通貨?��普�?", "潮?���?�干�??��；動�?", "妊�?中絶", "損害?���?�程度?��；死�?数?���?�行料", "?���?�）罰?��罰�?", "森林伐採", "細菌；微生物",
			"発生，勃発", "流行病?��蔓延", "�?候群?�?...現象", "直売店；�?�け口?���?�米】（電気�?�?��コンセント（≒【英】socket?�?", "香水?��香料", "歓迎会；受付；受�?",
			"受け取る人?��（臓器などの?��被提供�??", "熱�?な?��鋭敏な?���?しい", "そこ�? こ�?�?��きちんとした?��上品な", "穏やかな?��軽�?", "謙虚な?��質�?な?��身�?が低い", "高貴な?���?��??とした",
			"利己�?な?��≒self-centered?�?", "残�?�な?��厳しい", "ばかげた；法外な", "耳が聞こえな�?��≒hard of hearing?�?", "感謝して�?�?", "入念な?���?�っ�?",
			"粗い?��大まかな?��乱暴な", "苦�?��厳しい?��辛辣な?���?�りっぽ�?", "急進�?な?���?�本�?な", "�?団の?���?�同�?�", "外来の?��異国風の", "?��傾斜が?���?�な?���?��?な?��法外な",
			"�?�?��⇔deep 深�?��；�?�?な", "?�?...と?��平行�?�?�?to?��；類似した", "十�?にありそうな", "絶対�?な?��⇔relative 相対�?な?�?", "美的な?��美学の",
			"進行する；�?...を）続行する�?with?�?", "花が咲く；�??える", "を主張する", "と確信する?��（を?��賭ける", "を�?る；（を?���?�慢する", "に?�?...を）�??に頼�??�?for?��；（を?��懇願す�?",
			"妥協する；を危�?くす�?", "?��を?��尋�?��?", "叫ぶ?���?�鳴�?", "をいじめる；を�?�?", "?��を?��降りる?��⇔ascend 上がる）；受け継がれる", "は�??��ゆっくり進�?", "かが�??��傾く；をもたせかける",
			"を回転させる；（糸?��を紡ぐ；回転する", "溺死する?��を水浸しにする", "を�?割する?���?裂す�?", "を復活させる；復活�? �?", "ため息をつ�?", "控える", "?��を?��掃く；を�?�?する?���?�過する",
			"編み物をする；を結合する", "を詰め込�??��詰め込み勉強をす�?", "を消化する?��を�?解する?��を要�?する", "を抑える?��を抑圧する", "の気�?を害する?��（に?��違反す�?",
			"補償する?��≒make up?��；に償う", "を悪化させる?��を合�?�する；を混合す�?", "から成る?��を構�?�す�?", "を移植する�? を移住させる", "を暴く；を発掘す�?", "を取り�?�す；を抜粋する；を引用する",
			"を募る；に新人を補�??する", "に権利を与える；に題名を付け�?", "を任命する?��を�?定す�?", "を設置する?��を就任させ�?", "を施行する；を?�?...に?��強制する?�?on / upon?�?", "を実行す�?",
			"を（巧みに?��操る；を改ざんする", "を精製する?��を洗練する", "を獲得する，達成する；に達す�?", "探究", "態度?��見解?��見�?�し?��眺�?", "前提?��（～s?��（建物を含めた?��構�??", "統合；結束?���?貫性",
			"織物 ?��構�??", "?��議論などの?��筋道?��糸", "職人?��工芸家", "彫刻?��作品?�?", "�?体；�?�域?��天�?", "?��道路などの?��カーブ；曲�?", "人物の紹介；横顔；輪郭", "�?�?", "?��判断・評価の?��基�?",
			"高度?��標�?", "授業料（＝tuition fees?��；（�?�人?��指�?", "杭?��賭け��?��利害関�?", "知人?��面識；知�?", "会話?��講�?", "感謝（�?�気持ち?�?", "�?拝；賛�?", "用�?��警�?",
			"恐�?�；強�?嫌悪?��嫌な物?��人?��", "腐敗?��した状態）；衰�?", "�?陥?��不足", "?��～s?��軍隊?��集団", "墓；�?the ?��）死", "牧場?���?�米】大農場", "共和国?���?�和制", "【米】郡?���?�英】�?",
			"【米】小別荘；小さな家", "�?業?��貿 �?", "不�?��後�??", "絶�?", "噴霧?��液?��；噴霧器", "同情", "子孫?��子；�?�果", "皮質?��樹皮", "名声", "価値がある；立派な",
			"妥当な?��⇔invalid 妥当でな�?��；有効な", "徹底的な?���?�く�?�", "途方もな�?��莫大な?��すばらし�?", "経験的な?��経験主義の", "二次�?な?��中級�?�", "そ�?�後�?�", "生まれながらの?��固有�?�",
			"室�?の?���??部の?��⇔exterior �? 部の?�?", "裸の?��あり�?�ままの", "無罪の?��⇔guilty 有罪の?��；無邪気な?��無知の", "繊細な?��扱�?にくい?��もろい", "�? �?ま�?な", "壊れ�?すい?��虚弱な",
			"ひど�?��嫌な?��恐ろし�?", "より劣った（⇔superior よりすぐれた?�?", "恥じて", "中世�?�?��時代�?れ�?�", "厳しい?��いかめしい", "張り詰めた?��緊張した", "帝国の?��皇帝�?�",
			"壮大な?��見事な", "を統 合する；融合す�?", "を取り�?�れる?��を法人にする?��合併する", "を利用する?��≒make use of?�?", "を修正する?��を改正する", "を長引かせる", "を少なくする；減る",
			"をかき回す；を揺り動かす", "を引きずる?��ぐずぐずす�?", "?��を?��磨�?", "を［から?��取り去る；を裸にする", "を押し込�??��を絞る", "を捨て去る；（�?�など?��を放つ?��（涙�?��??��を流す",
			"?�?plug inで?��を電源に差し込�??��を差し込�?", "を歪める?��歪�?", "を混乱させる；を�?裂させる", "を荒らす?��を困惑させる", "を悪化させる?��悪化する（≒deteriorate?�?",
			"を�?止する?��≒do away with?�?", "を取り戻�?", "を及ぼす；を行使する", "に先行する；に優先す�?", "�?れる?��徐�??に弱ま�?", "?�?...と?��会話をする�?with?�?",
			"?��声?��を発する?��（�??えなど?��を述べ�?", "の要点を述べる；�?�輪郭を描�?", "�?応する；�?致する", "を指定する；を任命する", "に自信を持って�?�??��を保証する", "を安�?させ�?", "を�?�める",
			"を引き起こす?��を説得す�?", "に義務づける?��に恩恵を施�?", "に強�?�?", "を引き起こす?��を刺�?する", "【米】を風呂に入れる?��を浸�?", "出�?する", "?��を?��巡航する?��巡回す�?",
			"急上�??する?��空高く飛�?�", "を象徴する?��を記号で表�?", "を理解する", "議定書", "�?�?", "�?標；索�?", "?��商?��取引；（人と人との?��交�?", "断�?", "わずか（≒bit?��；�?部?���?数",
			"虫?��病原体；盗聴器?���?陥", "細菌；�??", "診断?��判断", "?�?...の?���?想?�?with?��；強迫観念", "悪夢?��不安感", "�?説?��矛盾", "皮�?", "悲しみ", "�?大限（⇔minimum �?小限?�?",
			"過剰?���?�?", "国�?���?the ?��）�?�米】辺�?地?��最先端", "避難?��所?��；保護", "【英】木材（≒【米】lumber?��；樹木", "奴隷制度?��苦役", "?��社会�?�?��階層制?��支配層",
			"?��官庁�?�?���??��事務�?", "監督�??��指導教員", "配�?��?", "反�??�?", "気晴らし?��娯楽", "祝宴?��大ごちそう?��楽しみ", "洗面器?��水たまり；流域", "下水", "?��集合的に?��景色?��背景", "�?",
			"目印?��画期的な出来�?", "記念碑；遺跡?����字�?", "?��人・動物の?��肉?��果�?", "衣�?", "ちらりと見えること", "輝き?��白熱?��幸福感", "優美；�?別?��恩寵", "�?実な?���?からの",
			"大�?な?��厚かましい", "飼�?ならされた", "もろ�?", "裸の", "?�?...に?���?�疫を持つ?�?to?��；�?�れ�?", "慢性の?��⇔acute 急性の?��；長引く", "徐�??の", "乏し�?��珍 しい",
			"有毒な?��中毒�?�の", "偶然の", "?�?...にとって?��無関係�?�?�?to?��；見当違�?の", "ささ�?な", "不可�?な?��⇔dispensable なくてもす�??�?", "原産の?���?�住�?�", "有史以前�?�?��旧式な",
			"神聖な?��信仰�?の厚い", "小売の?��⇔wholesale  卸売り�?�?�?", "大都市�?�?��首�?�圏�?�", "単純な?��率直な", "鮮�?かな?��生き生きとした", "際立った；未払いの", "を豊かにする",
			"を引き受ける；を保証する?��に�?手す�?", "を収容する?��を?�?...に?��適応させる?�?to?�?", "を集める?��を�?み立て る；集ま�?", "を�?�現する?��を統合す�?", "を織る?��を作り上げ�?",
			"を回収する；（データ?��を呼び出�?", "?��手?��をたたく；（に?��拍手す�?", "を引っかく?��を中止する", "を消す", "を縫�??��縫�?物をす�?", "しがみつく；くっつ�?", "?��を?��辞任する?��を放�?する",
			"を�?�っくりさせる（≒surprise?�?", "を呼び起こす", "を�?�確にする", "?��を?��告白する", "?��を?��祈る", "を許容する?���?��?�する?��≒put up with?�?", "をうらや�?",
			"?�?revenge oneselfまた�?�受身形で?��復讐す�?", "出発する?���?...から?��それる?�?from?�?", "を追�?抜く?��に追�?つく（≒catch up with?��；を襲�?",
			"を侵略する?��を侵害する?��に殺到する", "の�?部に入る；（を?��貫く；（に?���?�出する", "を同封する；を取り囲�?", "漏れる；を漏ら�?", "を�?潮させる；を水で流す?���?潮する", "輝く?��際立つ",
			"?��火山が）噴火する?��勃発する", "を染める?��染ま�?", "を止める?��止ま�?", "を停職?��停学?��処�?にする?��を中断する", "を上回�?", "?��を?��操縦する?��を?�?...へ?��向ける?�?to?�?",
			"航行す�? ?���?�路を示�?", "と矛盾する?��に反対意見を�?�?", "と主張する?��競�?", "を溶かす?��を�?解する?��溶ける", "努力する；争う", "遺産", "�?わさ", "韻�?��⇔prose 散�?��；詩",
			"原稿?���?�本", "台本?���?跡", "散�?��⇔verse 韻�?��；�??屈な話", "?��新聞などの?��見�?��?", "直�?", "真空?��空�?", "炎；情熱", "水�??��湿�?", "浸食；衰�?", "半島",
			"自殺?���?�殺�?行為", "?��宗教・道徳上�?�?��罪?���?�かなこと", "禁忌，タブ�?�", "�?怒；猛�?", "強欲", "�?�?", "悲惨?��苦難", "疫�??��（害虫などの?��異常発�?", "孤�?", "肝臓",
			"跡?��手がかり；小道", "?��座席間などの?���?�路", "洗濯?��物?��；クリーニング�?", "�?�?", "買�?得品?��取引；契�?", "?��～s?��歳入?��⇔expenditures 歳出?��；（～s?��収�?",
			"赤字，�? 足?���?陥", "�?人?��アマチュア?��⇔professional プロ?�?", "学部学�?", "大使?��使�?", "戦士", "戦争（行為?��；闘�?", "植物学?��（�?地方の?��植物", "人類学",
			"イ�?オロギー?���?�想傾�?", "自発�?な?��⇔compulsory 強制�?な?��；無償�?�", "自然発生的な?��無意識的な", "�?意�?�?���?�重な", "目立つ", "透�?�な?���?�快な", "表面�?な", "空洞�?�?��空虚な",
			"特有�?�?��特異な", "部�?�?な?��不�?�平な?��特に好きな", "きちんとした?��見事な", "�?暗い?��ぼんやりし�?", "代わりの?��≒alternative?��；交互�?�", "?��日常�?に?��当たり前の",
			"嫉妬深�?��用�?深�?", "敵意�?�ある?��敵の", "熟した；�?��?�し�?", " 妊�?した?���?...で?���?ちて�?る�?with?�?", "肥�?な?��⇔infertile?��barren 不毛�?�?�?", "猛烈な?��ど�?猛な",
			"徹底的な", "膨大な", "�?高�?�", "?�?...で?���?でて�?る�?in / at?��；に勝る", "膨張する?���?�れる?��を膨らませる", "跳ねる；反�?�? る；を弾ませる", "?��を?��歩き回�?",
			"はぐれる；迷�?", "?��他国へ?��移住す�?", "?��を?��つぶ�?く；�?�つぶつ?��不平を）�?�?", "?��を?��ささやく；ざわめ�?", "くすくす笑う", "を�?せさせる?��を詰まらせる；�?せる",
			"?�?...に?��眉を�?�そめる�?upon / at?�?", "�?なる，ほえる", "�?える", "�?える?��揺れ動�?", "?��顔�?�ひげなど?��をそる?��を削減す�?", "?��を?��誤解する", "をな�?める?��を和らげる",
			"を誘惑する", "を�?�かにする?��≒make fun of?��；をからかう", "?��を?��からか�??��を �?じめ�?", "を軽蔑する（≒look down on?�?", "を無視する；を軽視す�?",
			"をうっかり表す；を裏�??�?", "?�?...を）�?��? する?�?to?�?", "をつか�??��を奪�?取る?��を没収す�?", "を持って来る，�?�れて来�?", "?��を?��こする?��を塗る", "ぱた�?�たと動く?��羽ばたく",
			"?��を?��突っ込�??��没頭する?��陥�?", "を挿入する", "?�?dispose ofで?��を処�?する", "に耐え�?", "を妨げる", "?��を?���?�開する?��を取り戻�?", "を統合す�?", "�?�?食品?��主要産物",
			"大�?", "芽?��つぼみ", "植物?��植生", "手足", "しわ?��折り目", "感情?��感傷", "深�?悲しみ", "呪�?��悪�?", "拷問；苦痛（�?�種?�?", "慈悲?��幸�?", "�?�?�?",
			"前任�??��⇔successor 後継�???��；前のも�?�", "精神科医", "論文?��命題，テーゼ", "突然変異", "糖尿�?", "�?弾", "�?団?��（植物の?��房?��束", "盾?��防御物", "器具?��歯車；ギア",
			"船舶?��容器?��脈管", "戦術；策略", "崩壊；（神経）衰弱?��故�?", "再会（�?��?�?��；�?�結合", "結�?�目", "�?宙探査用ロケ�?ト；精査", "放�?能?��放�?�?", "�?剤?��平板", "蒸気；気�?",
			"温度計，体温�?", "署名；特徴", "三角形", "幾何学", "偉業?��妙技", "拍手?��喝�?�?", "�?光；壮観", "勤勉な?���?�念な", "まじめな?���?��?な", "?�?...に?���?実な?�?to?�?",
			"頑固な?��≒obstinate?��；不屈�?�", "厳しい?��硬直した", "硬直した?���??�?", "�?�?な", "?��何もせずに?���?�ら�?�らして�?�?", "ばかげた；口のきけな�?��無�?の", "肥�?した",
			"障が�?のある?��障がい�?用の", "不器用な?��扱�?にくい", "時間を守る", "ばかげた；不合�?な", "不安な?��落ち�?かな�?��ぎこちな�?", "不快な?��意地悪な", "�?たずらな", "きちんとした?��相当�?�",
			"決定的な?��断固とした", "真っすぐな?��正直な", "垂直の?��⇔horizontal 水平な?��；縦方向�?�", "陰気な?��薄暗い?��悲観�?な", "人目につかな �?��不�?�瞭な", "骨董の?��古風な",
			"唯�?の?��単独の?��独�?�?な", "純然たる?��真の?��すごい", "す�?�らし�?��驚くべ�?", "す�?�らし�?��立派な", "を�?に抱く；を大�?にする", "に�?養を与える；をはぐく�?",
			"を孵化させる?��孵化する；をたくら�?", "を拡大する", "に?�?...を）備え付ける�?with?�?", "?�?...に?���?�ける?�?in?��；を甘やかす", "?�?...に?��屈する�?to?�? ?��を放�?する?��を明け渡�?",
			"ひざまずく", "?�?...に?��つまずく?�?on / over?�?", "しおれる?��衰える?��を弱らせ�?", "忍�?�込�??���?�ろ�?�ろ�?��??���?��?", "痛�??���?...を）�??望する�?for?�?",
			"を�?つ?��≒wait for?�?", "を予知する", "を�?�らす?��を解明す�?", "を�?�どく恐れる", "を描�?", "を意味する?��重要である", "?��を?��誓う?���?�のしる",
			"を指図する?��を書き取らせる；を決定づける", "を暗唱する?��を詳述する", "登録する?���?�会する；を登録させ�?", "を実行する；を処刑す�?", "を偽�?する?���?�ふりをする", "を変�?させる；を偽�?",
			"を汚す?��に�?色する", "を縛る", "を（平手で?��たたく", "を省く；を�?�?", "?���?物など?��をひ�?", "を徐�??に�?し�?��?", "を�?�産させ�?", "?��火・光など?��を消す?��を全�?させ�?",
			"を修繕する；を改�?する", "?��人?��を?�?...のことで?��祝う?�?on?�?", "証明書?���?�許状", "百科事�?�", "伝�?", "傑�?", "詩歌；韻", "手段?���?�?", "鋳型；�?�質", "�?囲?��余地",
			"?�?the ?��）�?...の?��大半�?of?��；かさ；大�?", "些細なこと?��少量?��≒a little?�?", "�?剤", "?��薬の?��服用量；放�?線量", "�?管?��静脈（⇔artery 動脈?��；特質", "におい?��気�??",
			"巡礼�?", "行い", "【英】車両?��立ち�?振舞い?��輸�?��馬�?", "�?たず�?", "虐殺?��畜殺", "急ぐこと", "?���?�どの ?���?き；�?�?", "君主制?��君主国", "治世；統治",
			"相続人?���?...の?��後継�???�?to?�?", "許�?", "法律；立�?", "?�?the C-?���??閣?��戸�?", "�?棟；行政区", "余剰?��黒�?", "計算；算数", "水�??��≒quicksilver?��；�?M-?��水�?",
			"独�??��権?�?", "不和?��摩擦", "衝�?", "融合?���?��?", "大発見，飛躍的進歩", "壮観?��見世物?���?�英】（～s?��眼鏡", "高名な?��傑 出した", "注目に値する?��著名な",
			"悪名高い?��≒infamous?�?", "義務的な", "?��しがちな?��受けやすい?��責任があ�?", "?��する傾向がある?��傾�?�?", "静的な?��⇔dynamic 動的な?��；停滞し�?",
			"無限�?�?��⇔finite 有限の?��；無数の", "永�?の?�? 不変�?�", "�?しい?��鋭�?���?�性の?��⇔chronic 慢性の?�?", "突然の", "�?早�?", "かすかな", "優しい?��柔らか�?��微妙な",
			"湿気�?�ある", "湿っ�?", "腐った；不快な?���?�落した", "酸っぱ�?��不機嫌な?��不愉快な", "痛い?���?�が立って", "ど�?猛な?��容赦のな�?", "天然の?��未精製の?��粗野な", "おおよその",
			"中級�?�?��中間�?�", "職業の", "男らし�?", "女らし�?", "余�?な?��不�?要な", "�?大限�?�", "?��を?���?��??する?��を予想する", "?��を?���?��??する", "瞑想する?��をもくろ�?", "?��を?���?�いつ�?",
			"?��を?��推測する?��投機す�?", "と推定する；を前提とする", "を宣�?する?��を証明す�?", "を�?�表する", "を誓う?��を�?保にする", "?��と?��叫ぶ", "?�?...を）予�?購読する?�?to?�?",
			"?��を?��悼�??��（を?���?�?", "に憤慨 する", "?��を?���?き悲し�??��を後悔する", "あえぐ；�?...を）�?望する�?for?�?", "?��を?��吸�?", "を浸す；浸�?", "を（ある状態に?��する；を与え�?",
			"回転する?��循環する?��を回転させ�?", "を貫く，（穴?��を開ける；を洞察す�?", "を彫る；を�?り開�?", "?��注意など?��をそらす；を迂回させ�?", "を追放する?��を吐き出�?", "を暴行する；を攻�?する",
			"侵害?��侵入?��する", "?��受身形で?���?...に?���?�る?���?...の?��中毒になる�?to?�?", "同時に起こる?���?致する", "?��を?��上がる（⇔descend 下りる�?", "殺到する?���?�騰する",
			"蒸発する?��消散する?��を蒸発させ�?", "期限が�??れる", "を発酵させる；発酵する", "?��を?��合併する?��融合する；を融合させ�?", "を建てる；を直立させる", "に恩恵を与える；に感謝す�?",
			"名声?��（形容詞的に?��名声のある", "?�?the ?��）貴族（社会）；�?the ?��）支配階�?", "政治家?��≒statesperson?�?", "【米】（しばし�?�S-?��上院議員", "?��宗教上�?�?��信条",
			"活力；迫�?", "落�??��狼狽", "憂うつ", "苦痛；苦悩", "苦悩", "良�?", "軽蔑；恥辱", "軽蔑；軽蔑�?�対象", "無感動", "織物?��繊維?��産業?�?",
			"?��左右?��対称?��⇔asymmetry 非対称?��；調�?", "?�?the ?��）�?�戸際；端", "虫歯?���?�穴?��；空�?", "�?�?", "暴�?", "亡命?���???��；（国外）追放", "�?古学", "標本?��実�?",
			"�?飾?��品?�?", "器具�?式；機�?", "�?点?��傷", "日食，月食；（名声などの?��失�?", "天�?学", "航空?��学?�?", "速度", "混�?", "アンケー�?", "�?生虫", "職員?��人員",
			"?�?the ?��）�?�現?��到来", "しるし；代用硬貨?��商品券", "保険料；�?�レミア", "思�?��?別のある", "?�?...に?��用�?深�?�?of?�?", "?��状況などが）暗�?��（表�?が）険しい", "厳粛な ?��真剣な",
			"?�?...に?����疑的な?�?of / about?�?", "疑わしい?��疑って", "無�?な?��うぬぼれた", "無�?な?���?...を）顧みな�?�?of?�?", "無慈悲な?��断固とした?��無茶な", "�?弁な?��説得力のある",
			"�?怒した；猛烈な", "疲れ果てた；�?...に?��う んざりした�?of?�?", "悲観�?な?��⇔optimistic 楽観�?な?�?", "冷笑的な", "邪悪な?��いたずらな",
			"驚くべき；�?妙な?��単 数の?��⇔plural �?数の?�?", "異様な?��≒bizarre?�?", "�?字どおりの?��散�?�?な", "明白な?��⇔implicit?��；率直な", "暗黙�?�?��⇔explicit?��；�??在する",
			"ほっそりした?��わずかな", "総計�?�?��甚�?しい?��粗野な", "紫外線�?�", "空間�?�", "空�?て�?�?", "�?�?とした?��雄大な", "十�?すぎるほどの?���?�?", "裕福な?��豊富な", "を推論す�?",
			"を理解する?��を識別する", "を主張する", "の原因を�?...に?��帰する?�?to?��；を?�?...の?��作と認める�?to?�?", "?��薬など?��を処方する?��を規定す�?", "?�?...に?��従う?�?with?��；応じ�?",
			"?�?abide byで?��に従う?��を我�?�する?��住�?", "?�?...に?���?願する�?with?��；（を?��弁護する?��申し立て�?", "?��を?��説教す�?", "に興味を持たせる；陰�?を企て�?",
			"を�?...と?���?致させる�?with?��；を和解させ�?", "?�?...に?��介�?�する?�?in?��；介在する", "を制止する?��を規制する", "の自尊�?を傷つける", "を非難する",
			"�? 非難する?��（受身形で?��有罪を宣告される", "に反抗する?��を拒�?", "?�?...に?��反�?する?�?against?��；�?かつ�?", "を損な�?", "?��害など?��を�?わせ�?", "の価値を下げる；を降�?�する",
			"悪化する；を悪化させる", "を�?�落させる；を買収する；�?�落する", "を汚染する?��を堕落させ�?", "を抑圧する?��を悩ませる", "を押しつける?��押�?", "?�?...に?��乗り出す�?on?���? 乗船?��搭乗］する",
			"を点検する；を視察す�?", "を呼びつける", "?��を?��証�?する", "を迫害する?��を苦しめ�?", "に強要す�?", "?��抑えて�?たもの?��を�?発させ�?", "を解放する", "に授ける；に�?贈す�?",
			"精査?��監�?", "類推?��類似", "没頭?���?��?�観", "回想", "�?ぬぼ�?", "誤った�??え；虚偽", "偽�?", "�?介（なこと?��人?��?�?", "?��青少年の?��非行，犯罪", "人質", "?��民事）訴�?",
			"【米】弁護士?��代�?人", "令状?��十�?な根�??��証明書", "証�??��証�?", "?��陪審の?��評決?��評価", "?���?��? ?��s?��制�?��認可", "迷信", "民話?��民俗学", "逸話", "修辞（法）；美辞麗句",
			"露店；失�?", "部�?", "合�?�；総合?��⇔analysis �?析�?", "結束?��結合", "遺伝；世襲", "大災害?���?��?", "窮状", "ひとりで�? ること?��孤独", "厳しい試練", "暴政?��専制国家",
			"検閲", "衛生?��状態）；健康�?", "【米】（政策上�?�?��主義?��教義", "外交?��的手�?��?", "実�?", "君主?���?�英】ソブリン金貨", "本物の?��信頼できる", "合法的な?��妥当な", "�?解できる",
			"生来の", "独創�?な?��利発な", "�?雑な", "�?質の?��⇔heterogeneous 異質の?�?", "単調な", "絶え間のな�?", "ひっきりなし�?�?��永続的な", "差し迫っ�?", "もっともらしい",
			"恣意的な", "予備の?��準備の", "?�?...が）�?けて�?�? ?�?in?��（≒lacking?�?", "?�?...より?��下位�?�?�?to?��；副次�?な", "封建時代?��制度?��の?��封建�?な", "�?れた",
			"致命�?な?��死すべき（⇔immortal 不死の?�?", "金銭�?な?����融�?�", "浪費する?��法外な", "めま�?がする；当惑した", "青少年の", "匿名�?�", "互換性のある?��矛盾しな�?��気が合う",
			"至る所にある", "神�?�?��神にささげる", "しらふの?���?度のある", "熱�?な"
	};
}
